import Head from "next/head";

export default function AppHead({
  title = "Create Next App",
  description = "Generated by create next app",
  icon = "/favicon.ico",
}) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description} />
      <link rel="icon" href={icon} />
    </Head>
  );
}
