import Head from "next/head";
import { MainFooter, MainHeader } from "../components";

export default function Home() {
  return (
    <div className=" flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" min-h-screen"></main>
    </div>
  );
}
